services:
  - type: web
    name: cyber-shield-siem
    runtime: python
    repo: https://github.com/poojariHimasri/cyber-shield-siem
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 dashboard.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        value: cyber-shield-production-secret-key
      - key: PORT
        value: 10000

